"""
Django settings for brasserie project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(Path(BASE_DIR) / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
# En production, stocker dans une variable d'environnement :
# export DJANGO_SECRET_KEY='votre-clé-secrète'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'q_4ax!5xthr0(s39krmc&(b%5=8y7fd+kp&_^909gicj7q+03=')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1').split(',')

csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
if csrf_origins:
    CSRF_TRUSTED_ORIGINS = csrf_origins.split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'brassin',
    'crispy_forms',
    'crispy_bootstrap4',
    'bootstrap_datepicker_plus',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'brasserie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brasserie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Formats de date/heure
TIME_FORMAT = 'H:i'
DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = [
    '%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y',
]

# Fichiers media (uploads)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Fichiers statiques
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

# Email (désactiver le backend console en production)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Authentification
LOGIN_URL = '/brasserie/connexion/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/connexion/'

# Session : 8h, expiration à la fermeture du navigateur
SESSION_COOKIE_AGE = 28800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True  # Inaccessible au JavaScript (protection XSS)

# Sécurité production (HTTPS uniquement sur PythonAnywhere)
SECURE_SSL_REDIRECT = False                  # Redirige HTTP → HTTPS
SECURE_HSTS_SECONDS = 31536000             # Force HTTPS pendant 1 an
SECURE_HSTS_INCLUDE_SUBDOMAINS = True      # Inclut les sous-domaines
SECURE_HSTS_PRELOAD = False                 # Autorise le preloading HSTS
SESSION_COOKIE_SECURE = False               # Cookie session uniquement en HTTPS
CSRF_COOKIE_SECURE = True                  # Cookie CSRF uniquement en HTTPS
X_FRAME_OPTIONS = 'DENY'                   # Interdit l'intégration en iframe
SECURE_CONTENT_TYPE_NOSNIFF = True         # Empêche le sniffing de type MIME