# Generated by Django 2.1 on 2021-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brassin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='etiquette',
            field=models.ImageField(blank=True, null=True, upload_to='recettes'),
        ),
    ]
