# Generated by Django 2.1 on 2021-04-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brassin', '0002_auto_20210405_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermenteur',
            name='diametre',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
