# Generated by Django 3.2.13 on 2024-03-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brassin', '0003_fermenteur_diametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brassin.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='acide_alpha',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
