# Generated by Django 3.2.13 on 2026-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brassin', '0004_auto_20240304_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brassin',
            name='ingredient',
            field=models.ManyToManyField(blank=True, through='brassin.BrassinIngredient', to='brassin.Ingredient'),
        ),
    ]
